project_name: git-credential-substitute
env:
  - GO111MODULE=on
builds:
  - main: .
    binary: git-credential-substitute
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows 
    goarch:
      - amd64

archives:
  - name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      darwin: macOS
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto

# homebrew
brews:
  - description: "git credential helper, which switches git credentials for the username/organization."
    github:
      owner: sadayuki-matsuno
      name: homebrew-git-credential-substitute.
    homepage: "https://github.com/sadayuki-matsuno/git-credential-substitute"
    install: |
      bin.install "git-credential-substitute"
